Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/8/2023
Var
// Seção de Declarações das variáveis 
comp, acres: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("O quanto comprou em dinheiro? ")
Leia (comp)
acres <- comp * 1.6
Escreva ("O valor total com imposto será de: US$", acres:6:2)

Fimalgoritmo